### ISSUE TITLE
conda install faiss-gpu -c pytorch

### ISSUE THREAD

**Issue by flyyyyer** [TerenceCYJ/SO-HandNet#2]
Can I install the faiss-gpu on 2080 Ti, cuda 10.1？

**Comment by TerenceCYJ** [comment]
You can try `conda install faiss-gpu cudatoolkit=10.0 -c pytorch`, according to [faiss/INSTALL.md](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md).
