### ISSUE TITLE
Missing packages in installation guide

### ISSUE THREAD

**Issue by SunXuan90** [TerenceCYJ/SO-HandNet#3]
In installation guide:

> pip install numba matplotlib h5py scipy donimate visdom horound libnccl2 libnccl-dev tqdm

`donimate`, `horound`, `libnccl2` and `libnccl-dev` cannot be found on PYPI.

Is `donimate` actually `dominate`, `horound` actually `horovod`?

Should `libnccl2` and `libnccl-dev` be installed by `apt` or other software manager rather than `pip`? Or should install `nccl` from `pip` instead?

Thank you!

**Comment by TerenceCYJ** [comment]
Thank you for your interest! I've corrected the README.md.
As for `nccl`,  you can refer to [https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html](https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html).
