### ISSUE TITLE
situation I face/请教的问题

### ISSUE THREAD

**Issue by zhaozhangning** [TerenceCYJ/SO-HandNet#5]
when I run your code,something wrong show up.Guess its version of the faiss is not matching.Could you please tell me your version of faiss？thanks so much！/当我运行这个代码，有一些问题。我觉得应该是faiss的版本不对，可否麻烦您告知我一下您使用的faiss版本呢？万分感激
![AF0B119488D5607B1460BD98AE82C57C](https://user-images.githubusercontent.com/82579568/114851325-4a6b1b80-9e14-11eb-8b2d-75fcfe864d7e.jpg)

**Comment by TerenceCYJ** [comment]
Hi. Could you refer to [this issue](https://github.com/TerenceCYJ/SO-HandNet/issues/2#issuecomment-564998271l)?

**Comment by zhaozhangning** [comment]
> 你好。你能谈谈[这个问题](https://github.com/TerenceCYJ/SO-HandNet/issues/2#issuecomment-564998271l)吗？![image](https://user-images.githubusercontent.com/82579568/114964314-0f62f980-9ea1-11eb-90f0-55a1543f15e0.png)
我是按照您所描述的环境
        conda create -n sohand python=3.6
	source activate sohand
	conda install pytorch torchvision cudatoolkit=8.0 -c pytorch
	conda install faiss-gpu -c pytorch
	pip install --upgrade pip
分别在linux上的终端安装好了环境，准备运行代码的时候出现如下的错误：

![image](https://user-images.githubusercontent.com/82579568/114964550-8b5d4180-9ea1-11eb-9c73-c78c7d1cfac2.png)


我猜测是驱动版本跟运行版本不一致，所以我把您之前描述的代码改了一下：
conda install pytorch torchvision cudatoolkit=8.0 -c pytorch改成conda install pytorch torchvision cudatoolkit=11.0 -c pytorch

重新运行了之后出现了如下的错误

![image](https://user-images.githubusercontent.com/82579568/114964606-a62fb600-9ea1-11eb-9c15-bde491fa39ad.png)

所以我猜测是faiss的版本不对导致的，我想问问当时您用的faiss版本是怎么样的？
